spring:
  application:
    name: BE

  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
  server:
    port: 8080
jwt:
  secret: 12345678901234567890123456789012
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

traveloka:
  base-url: https://www.traveloka.com
  route-prefix: vi-vn
  locale: vi-VN
  currency: VND
  geo-id: "10010169"
  geo-name: "Đà Lạt"
  num-adults: 1
  num-rooms: 1
  rows-per-page: 25
  check-in-offset-days: 7
  stay-nights: 1
  search-api-path: /api/v2/hotel/searchList
  search-spec: "13-06-2026.14-06-2026.1.1.HOTEL_GEO.10010169.Đà%20Lạt.2"
  request-body: ""
  request-body-file: traveloka/search-list-request.json
  cookie: 'countryCode=VN; _gcl_au=1.1.929414034.1781253119; _gid=GA1.2.2106106109.1781253119; _fwb=94mMk1xnzDEIshzr2PDtiF.1781253119429; __lt__cid=27192cfb-1228-4f15-ae57-d92b54844439; _yjsu_yjad=1781253119.6d2ee430-6eb2-4a5d-95cf-25e1d195443a; _kmpid=km|www.traveloka.com|1781253119577|83d807a4-47be-431f-878d-30d60ee0ddcf; _kmpid=km|traveloka.com|1781253119577|83d807a4-47be-431f-878d-30d60ee0ddcf; _ly_su=1781253119.6d2ee430-6eb2-4a5d-95cf-25e1d195443a; _tt_enable_cookie=1; _ttp=01KTXFB7MMSPMPJK656BM9WB9T_.tt.1; _fbp=fb.1.1781253119690.48673137772636516; _pin_unauth=dWlkPU1HSTVNekEyTURZdE56ZGtNQzAwWkRFM0xUa3dPV1V0TUdFMU5ERTFNbVJtT1dVeQ; _cs_ex=1760605804; _cs_c=1; clientSessionId=T1-web.01KTY84Y3SPEFA0XMMDYK9NSDN; tv_cs=1; tv-repeat-visit=true; tv_user={"authorizationLevel":100,"id":null}; __lt__sid=46c10688-bf80356d; aws-waf-token=95e6dc42-b646-4b3e-a4ca-4b393aafa758:NQoAkwR0074DAAAA:haae0Dn96IDVxQzPlEF/wP5rhIMSmq5jKyMMdZTzxchx85EI6p9YSOSBIJPNrnjlaJE+7vkwTvBp4T2SI+xDAgjtI7rjzXEteODq9t3j22z27IxRScErj/SQ3s1fjIl3GoLS5vOKRgQTXaKw2T0ySMa7RMM3jgrUyKHEZmF57hIDrBA52LqPf+b54HDi5dqGzeCKpev9bgbVT8hc28x2NAv5yIjeIq6CZuIeXG9qaLXKcCjsSb+DK2NV; _gat_UA-29776811-12=1; tv_mcc_id=01KTYBFY7Q275M2Z7GJNTG8KKE; g_state={"i_l":0,"i_ll":1781282653593,"i_b":"oOZ1DiqnlWVkn4pv01AA1fNAGV+hSJHk9g7+gp/gn/A","i_e":{"enable_itp_optimization":0},"i_et":1781253119248}; tvs=qgdHX7GvehrD9XH5a3S4PXWKx93/3Xi103f/kPpnhg1IQez7AjqOPow88qqCMiL7CqvJjpn5Z2svD8QZzAmUN07gmFQkK2qgsdbWEYgFfB5uk0fUx7sD+NMcK9CmgVocrii3pNJ2kgG/MGUmzAKhwmCIB1NXpx+g05VnrVlNT1r5u09yAru40JsnILlCW/Axrly5judQ57uRp/AfzZ5xCn02WGFsB1Vm7c/D3KzX4nd294VeX/RgsfDAJ6sV3mPqg43qby0ICwtMQsEEYY/mJ063CCJo+Z+R9n/X0FgUdFdWi6NKpEDgL3xVNnQjLp40FhrkmWFU4Pn0+ElScsbvvTJEQsBrPWhemFWfDuZF7MmsStRtF7qElnLdB0dOiDupi5amsVyiwF7TuFQalSPLeD0Uum36nobT+QnfzO2VKiBR5ZjDc0B2wucQ1FzLnuVi3WGlnSOcmvWmaBAeRxrpnumaURC0pEZeeQCe7188J/C6CG27OJSUuklXWI0BIrNRCFnqYYpMSCRL8yPQAXFPMQ==; tv_lt=1781282659413; ttcsid_CFNI0BRC77UEUGLEG00G=1781279152134::c2rCng0I83BzNvxfhWF4.2.1781282660010.1; amp_1a5adb=6-dGA5WMzfMhKvd6J5htdt...1jqu85i3m.1jqubgo01.4d.3.4g; amp_f4354c=f1gaQMIytdZBqzgN1pey3m...1jqu85i3p.1jqubgo07.0.3.3; wcs_bt=s_2cb982ada97c:1781282660; _rdt_uuid=1781253119523.f74b066c-2155-4e2f-accd-56f72091c644; __rtbh.lid=%7B%22eventType%22%3A%22lid%22%2C%22id%22%3A%22YXsfJIGJI2g9gfTXCaAl%22%2C%22expiryDate%22%3A%222027-06-12T16%3A44%3A20.785Z%22%7D; _derived_epik=dj0yJnU9Yy1DY0pQbHVzMkM1cDlwMjg3cE5JMWc4bE1QR09QakImbj04Z05lcjB4eEJ3RUVkN2c4S2R6NUtRJm09MSZ0PUFBQUFBR29zTjJZJnJtPTEmcnQ9QUFBQUFHb3NOMlkmc3A9Mg; cto_bundle=dJJQvV9ZdjdyUENKclBsRTZIajAxcCUyRlFvZ3dxUHdzSlJ4bTB4WnhoVlFIMlhRQm5xWHFmJTJGOVFlVXdWaHNJZDFJclhXUTNyaG9PV2QyeWdrdkFDaTVKYmFydWJLRlF2c3Rxd1l0JTJCV0ppT2I3eFBlYUJrMWhIRzBneUh6bzNFSVZyc3p5UFo5OU9mN0NBNWdsaDdZY1hXQ0JZTkElM0QlM0Q; datadome=J9c6nSKVZKxZMUkkLjsxUS_Eh02pLBOY0ch8LKLxO3g~dcc48~OjSpn930hnI0TKuFptwxW6VhtyxZNDnRy~eM3fDOQTMwdNUeaY07nCPihj74dg_RH~nkm~rrHET7kv; _ga=GA1.2.990325149.1781253119; tvl=qgdHX7GvehrD9XH5a3S4PUiOJGezXQ9yizVaSxTklwrLYY64AE4apiD1qmHRGaV8gGAQoV6xR5wi1hxtboYegx0JoHbuxL9J5IDMykh7yrn/kmgjvZe3CXlrOt5A94G1h8SGYm0D03zEW7S7g02l9zkAPbkMGQ6AJj+0Bs51j2d09mChRGdTOLst91XCJvaNb9BOFN5mX79zxx0eAPx7mmYAJe5kHkxbBKDPGEm2RBwoo2a2Axi4zbIdElhmy4dNNjW+NkVXC2BoUdiADUg/No5yW85bVtBDzvq/xMZJueXM0WMA1zSky7I1/5su3gOqU4uuATjUL/xv+Zf6AMMbg7E3Q5vJP9xMX0P4ctkpCrUiE4Xv9aRQYykpxayhdfUOxbVWc9mUJC6U6r8wkx04c+4CDTx/jJt5ZXoEQTwGFtnwCcclLuzShsrKowlKXKLI7veLx2+f12FgAD3Xp2DyrpCu+WzMsWt0Z5lOvRtZeAR6V/NjpjnmEZgYmHZdWc+HH+WzeIeWPbsPfCDu9N+3vpUF6IEMclGMvtdbudeGbc8=; sen_t=Adt8GUIGp9Ri/vl1qiYNjuaXOepINY9UbIH09ug/vAFZhIag7VuxT/RGC2IJG5NxCceBL4L9GPOTwT8LzpmMDMtI+mXr/dwnICATEdTe6OIfVdQ5hm7e4Ts4g2fD; ttcsid=1781279152135::YQWe1dGxu3lVFelpQ7oa.3.1781282676116.0::1.3497893.3508365::3523960.31.1202.154::2170523.27.0; ttcsid_CUM82PBC77U4QKJNCRL0=1781279155679::5xFsoURidkdwKKyf2XmC.3.1781282676116.1; _dd_s=rum=0&expire=1781283577024&logs=1&id=8318881e-5ea8-4fb4-945d-35872949221c&created=1781279133681; tvo=L2FwaS9zZW4vc3M=; _ga_RSRSMMBH0X=GS2.1.s1781279154$o3$g1$t1781282677$j4$l0$h1211720490'
