spring:
  application:
    name: BE

  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
  server:
    port: 8080
jwt:
  secret: 12345678901234567890123456789012
  access-token-expiration: 900000
  refresh-token-expiration: 604800000